# Generated by Django 2.0.5 on 2020-05-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0002_auto_20200423_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderhmchapterimage',
            name='splider_img_url',
            field=models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='爬取图片URL'),
        ),
    ]
