# Generated by Django 2.0.5 on 2020-05-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0004_auto_20200505_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderhmchapterimage',
            name='content_img',
            field=models.ImageField(blank=True, height_field='img_height', max_length=2000, null=True, upload_to='hanman/content/%Y/%m%d/%H/', verbose_name='图片', width_field='img_width'),
        ),
    ]
