# Generated by Django 2.0.5 on 2020-07-04 10:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spiderdata', '0005_auto_20200505_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderWebUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_url', models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='web网址')),
                ('url_title', models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='网站标题')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '网址收录',
                'verbose_name_plural': '网址收录',
            },
        ),
    ]
