# Generated by Django 2.0.5 on 2020-07-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0007_auto_20200704_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderweburl',
            name='is_spider',
            field=models.BooleanField(default=False, verbose_name='是否可以爬去获得新网址'),
        ),
    ]
