# Generated by Django 2.0.5 on 2020-07-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0008_spiderweburl_is_spider'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopySpiderWebUrl',
            fields=[
            ],
            options={
                'verbose_name': '网址收录之可以爬取新网址',
                'verbose_name_plural': '网址收录之可以爬取新网址',
                'proxy': True,
                'indexes': [],
            },
            bases=('spiderdata.spiderweburl',),
        ),
        migrations.AlterField(
            model_name='spiderweburl',
            name='is_spider',
            field=models.BooleanField(default=False, verbose_name='是否可以爬取获得新网址'),
        ),
    ]
