# Generated by Django 2.0.5 on 2020-07-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0010_spiderweburl_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderweburl',
            name='is_already_spider',
            field=models.BooleanField(default=False, verbose_name='是否已爬取'),
        ),
    ]
